CRM/CRM.AppWebMVC/Models/ErrorViewModel.cs
namespace CRM.AppWebMVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CRM/CRM.AppWebMVC/Controllers/CustomerController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using CRM.DTOs.CustomerDTOs;

namespace CRM.AppWebMVC.Controllers
{
    public class CustomerController : Controller
    {
        private readonly HttpClient _httpClienteCRMAPI;

        // constructor que recibe una instancia de IHttpClienteFactory para crear el cliente HTTP
        public CustomerController(IHttpClientFactory httpClientFactory)
        {
            _httpClienteCRMAPI = httpClientFactory.CreateClient("CRMAPI");
        }
        // metodo para mostrar la lista de clientes 
        public async Task<IActionResult> Index(SearchQueryCustomerDTO searchQueryCustomerDTO, int CountRow = 0)
        {
            //configuracion de valores por defecto para busqueda
            if (searchQueryCustomerDTO.SendRowCount == 0)
                searchQueryCustomerDTO.SendRowCount = 2;
            if (searchQueryCustomerDTO.Take == 0)
                searchQueryCustomerDTO.Take = 10;
            var result = new SerchResultCustomerDTO();

            //Realizar una solicitud HTTP POST para buscar clientes en el servicio web
            var response = await _httpClienteCRMAPI.PostAsJsonAsync("/customer/search", searchQueryCustomerDTO);
            if (response.IsSuccessStatusCode)
                result = await response.Content.ReadFromJsonAsync<SerchResultCustomerDTO>();
            result = result != null ? result : new SerchResultCustomerDTO();

            // configuracion de valores para la vista
            if (result.CountRow == 0 && searchQueryCustomerDTO.SendRowCount == 1)
                result.CountRow = CountRow;
            ViewBag.CountRow = result.CountRow;
            searchQueryCustomerDTO.SendRowCount = 0;
            ViewBag.SearchQuery = searchQueryCustomerDTO;
            return View(result);

        }
        // metodo para mostrar los detalles de  un cliente
        public async Task<IActionResult> Details(int id)
        {
            var result = new GetIdResultCustomerDTO();

            // Realizar una solicitud HTTP GET  para obtener los detalles del cliente por ID
            var response = await _httpClienteCRMAPI.GetAsync("/customer/" + id);
            if (response.IsSuccessStatusCode)
                result = await response.Content.ReadFromJsonAsync<GetIdResultCustomerDTO>();

            return View(result ?? new GetIdResultCustomerDTO());

        }
        // metodo para mostrar el formulario de creacion de un cliente
        public ActionResult Create()
        {
            return View();
        }
        // metodo para procesar la creacion de un cliente
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateCustomerDTO createCustomerDTO)
        {
            try
            {
                // realizar una solicitud HTTP POST para crear un nuevo cliente
                var response = await _httpClienteCRMAPI.PostAsJsonAsync("/customer", createCustomerDTO);
                if(response.IsSuccessStatusCode)
                {
                    return RedirectToAction(nameof(Index));
                }
                ViewBag.Error = "Error al intentar guardar el registro";
                return View();
            }
            catch(Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View();
            }
        }
        //metodo para mostrar el formulario de edicion de un cliente 
        public async Task<IActionResult> Edit(int id)
        {
            var result = new GetIdResultCustomerDTO();
            var response = await _httpClienteCRMAPI.GetAsync("/customer/" + id);

            if (response.IsSuccessStatusCode)
                result = await response.Content.ReadFromJsonAsync<GetIdResultCustomerDTO>();

            return View(new EditCustomerDTO(result ?? new GetIdResultCustomerDTO()));

        }
        // metodo para procesar la edicion de un cliente
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult>Edit(int id, EditCustomerDTO editCustomerDTO)
        {
            try
            {
                // realizar una solicitud HTTP PUT para editar el cliente
                var response = await _httpClienteCRMAPI.PutAsJsonAsync("/customer", editCustomerDTO);
                if ( response.IsSuccessStatusCode)
                {
                    return RedirectToAction(nameof(Index));
                }
                ViewBag.Error = "Error al intentar el registro";
                return View();
            }
            catch(Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View();
            }
        }
        //metodo para mostrar la pagina de confirmacion de eliminacion de un cliente
        public async Task<IActionResult> Delete(int id)
        {
            var result = new GetIdResultCustomerDTO();
            var response = await _httpClienteCRMAPI.GetAsync("/customer/" + id);
            if (response.IsSuccessStatusCode)
                result = await response.Content.ReadFromJsonAsync<GetIdResultCustomerDTO>();

            return View(result ?? new GetIdResultCustomerDTO());
        }
        //metodo para procesar la eliminacion de un cliente
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id, GetIdResultCustomerDTO getIdResultCustomerDTO)
        {
            try
            {
                //realizar una solicitud HTTP DELETE para eliminar un cliente por ID
                var response = await _httpClienteCRMAPI.DeleteAsync("/customer/" + id);
                if(response.IsSuccessStatusCode)
                {
                    return RedirectToAction(nameof(Index));
                }
                ViewBag.Error = "Error al intentar eliminar el regitro ";
                return View(getIdResultCustomerDTO);
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View(getIdResultCustomerDTO);
            }
        }
          
           

      
         

    }
}

CRM/CRM.AppWebMVC/Controllers/HomeController.cs
using CRM.AppWebMVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CRM.AppWebMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CRM/CRM.AppWebMVC/Views/Customer/Create.cshtml
@model CreateCustomerDTO
@{
    ViewData["Title"] = "Create";
}
<h1>Crear</h1>
<h4>Cliente</h4>
<hr />
<form asp-action="Create">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="row">
        <div class="col-4">
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="col-4">
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>

            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <textarea asp-for="Address" class="form-control"></textarea>
                <span asp-validation-for="Address" class="text-danger"></span>

            </div>
        </div>
    </div>
    <br />
    <div class="row-cols-6">
        <div class="form-group">
            <input type="submit" value="Crear" class="btn btn-primary" />
            <a asp-action="Index" class="btn btn-secondary">Cancelar</a>
        </div>
    </div>
</form>
@section Scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

CRM/CRM.AppWebMVC/Views/Customer/Delete.cshtml
@model GetIdResultCustomerDTO
@{
    ViewData["Title"] = "Delete";
}
<h1>Eliminar</h1>

<h3>¿Estas seguro que deseas eliminar el cliente?</h3>
<div>
    <h4> Cliente</h4>
    <div class="row">
        <div class="col-4">
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" disabled class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
         <div class="col-4">
               <div class="form-group">
                    <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" disabled class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>

               </div>
         </div>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <textarea asp-for="Address" disabled class="form-control"> </textarea>
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
        </div>
    </div>
    <br />
    <form asp-action="Delete">
        <div class="row-cols-6">
            <div class="form-group">
                <input type="submit" value="Eliminar" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-secondary">Cancelar</a>
            </div>
        </div>
    </form>
</div>

CRM/CRM.AppWebMVC/Views/Customer/Details.cshtml
@model GetIdResultCustomerDTO
@{
    ViewData["Title"] = "Details";
}
<h1>Detalle</h1>

<h4>Cliente</h4>
<hr />
<form asp-action="Details">
    <div asp-validation-summary="ModelOnly"class="text-danger"></div>
    <input asp-for="Id" type="hidden" />
    <div class="row">
        <div class="col-4">
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" disabled class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="col-4">
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" disabled class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <textarea asp-for="Address" disabled class="form-control"></textarea>
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            
        </div>
    </div>
    <br />
    <div class="row-cols-6">
        <div class="form-group">
            
            <a asp-action="Index" class="btn btn-secondary">Ir a ver clientes </a>
        </div>
    </div>

</form>
@section Scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

CRM/CRM.AppWebMVC/Views/Customer/Edit.cshtml
@model EditCustomerDTO
@{
    ViewData["Title"] = "Edit";
}
<h1>Edit</h1>

<h4>Cliente</h4>
<hr />
<form asp-action="Edit">
    <div asp-validation-summary="ModelOnly"class="text-danger"></div>
    <input asp-for="Id" type="hidden" />
    <div class="row">
        <div class="col-4">
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="col-4">
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <textarea asp-for="Address" class="form-control"></textarea>
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            
        </div>
    </div>
    <br />
    <div class="row-cols-6">
        <div class="form-group">
            <input type="submit" value="Modificar" class="btn btn-primary" />
            <a asp-action="Index" class="btn btn-secondary">Cancelar</a>
        </div>
    </div>

</form>
@section Scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

CRM/CRM.AppWebMVC/Views/Customer/Index.cshtml
@model SerchResultCustomerDTO
@{
    ViewData["Title"] = "Index";
    var modelSearchQuery = ViewBag.SearchQuery as SearchQueryCustomerDTO;
}
<partial name="SearchQuery" model="modelSearchQuery"/>
<partial name="SearchResult" model="Model.Data"/>

CRM/CRM.AppWebMVC/Views/Customer/SearchQuery.cshtml
@model SearchQueryCustomerDTO // declara el modelo esperado para esta vista
@{
    // obtiene el valor de CountRow de la Viewbag
    int totalRegistros = (int)ViewBag.CountRow;
    // calcular el numero total de paginas 
    int totalPaginas = (int)Math.Ceiling((double)totalRegistros / Model.Take);
}
<h4>Buscar Cliente</h4>
<hr/>
<div class="row">
    <form asp-action="Index">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input asp-for="Skip" type="hidden" id="txtSkip"/>
        <input asp-for="Skip" type="hidden" id="txtSkip"/>
        <input name="CountRow" value="@totalRegistros" type="hidden"/>
        <div class="row">
            <div class="col-4">
                <div class="form-group">
                    <label asp-for="Name_Like"class="control-label"></label>
                    <input asp-for="Name_Like"class="form-control" />
                    <span asp-validation-for="Name_Like" class="text-danger"></span>
                </div>
            </div>
            <div class="col-4">
                <div class="form-group">
                    <label asp-for="LatName_Like" class="control-label"></label>
                    <input asp-for="LatName_Like" class="form-control"/>
                    <span asp-validation-for="LatName_Like" class="text-danger"></span>
                </div>
            </div>
            <div class="col-2">
                <div class="form-group">
                    <label asp-for="Take" class="control-label"></label>
                    <select asp-for="Take" class="form-control">
                        @for(var i= 10; i<1000; i += 10)
                        {
                            if(i== Model.Take)
                            {
                                <option selected value="@i">@i</option>
                            }
                            else
                            {
                                <option value="@i">@i</option>
                            }
                        }
                    </select>
                    <span asp-validation-for="Take" class="text-danger"></span>
                </div>
            </div>
        </div>
        <br/>
        <div class="row">
            <div class="col-12">
                <div class="form-group">
                    <input type="submit" id="btnSearch" value="Buscar" class="btn btn-primary"/>
                    <a asp-action="Create" class="btn btn-primary">Ir Crear</a>
                </div>
            </div>
        </div>
        <br/>
        <div class="row" style="overflow:auto !important">
            <nav aria-label="Page navigation example">
                <ul class="pagination">
                    @{
                        int skipAnte = Model.Skip > 0 ? Model.Skip - Model.Take : 0;
                        int skipMax = 0;
                    }
                    <li class="page-item"><a class="page-link" data-skip="@skipAnte" href="#" onclick="paginacion(this)">Anterior</a></li>
                    @for  (var i=0; i< totalPaginas; i++)
                    {
                        int skip = i * Model.Take;
                        int numPag = i + 1;
                        if (skip != Model.Skip)
                        {
                            <li class="page-item"><a class="page-link" data-skip="@skip" href="#" onclick="paginacion(this)">@numPag</a></li>

                        }
                        else
                        {
                            <li class="page-item active"><a class="page-link" data-skip="@skip" href="#" onclick="paginacion(this)">@numPag</a></li>
                        }
                        skipMax = skip;
                    }
                    @{
                        int skipSi = Model.Skip + Model.Take;
                        skipSi = skipSi > skipMax ? skipSi - Model.Take : skipSi;
                    }
                    <li class="page-item"><a class="page-link" data-skip="@skipSi" href="#" onclick="paginacion(this)">Siguiente</a></li>
                </ul>
            </nav>
        </div>
        <div class="row-cols-6">
            <span>Total registros:@totalRegistros</span>
        </div>
    </form>
</div>
<script>
function paginacion(li) {
    const skip = li.getAttribute("data-skip");
    const btnSearch = document.getElementById("btnSearch");
    const txtSkip = document.getElementById("txtSkip");
    const txtSendRowCount = document.getElementById("txtSendRowCount");
    txtSkip.value = skip;
    txtSendRowCount.value = 1;
    btnSearch.click();
}

</script>

CRM/CRM.AppWebMVC/Views/Customer/SearchResult.cshtml
@model IEnumerable<SerchResultCustomerDTO.CustomerDTO>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(item => item.Name)
            </th>
            <th>
                @Html.DisplayNameFor(item => item.Address)
            </th>
            <th> Acciones</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                    
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Address)
                </td>
                <td>
                    @Html.ActionLink("Modificar", "Edit", new{ id=item.Id})|
                    @Html.ActionLink("Ver","Details", new { id=item.Id})|
                    @Html.ActionLink("Eliminar", "Delete", new {id=item.Id})
                </td>
            </tr>
        }
    </tbody>
</table>

CRM/CRM.AppWebMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CRM/CRM.AppWebMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CRM.AppWebMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CRM.AppWebMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CRM.AppWebMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area=""asp-controller="Customer" asp-action="Index">Clientes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - CRM.AppWebMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>